version: "3.9"
services:
  api-service:
    build: ./api-service
    ports:
      - "5000:5000"
    restart: always
  web-service:
    build: ./web-service
    ports:
      - "3000:3000"
    restart: always