version: "3.9"
services:
  api-service:
    build: ./api-service
    ports:
      - "5000:5000"
    restart: always
  web-service:
    build: ./web-service
    ports:
      - "3000:3000"
    restart: always
  database-service:
    image: mongo:latest
      #environment:
      #  MONGO_INITDB_ROOT_USERNAME: root
      #  MONGO_INITDB_ROOT_PASSWORD: toor
    ports:
      - 27017:27017
    volumes:
      - ~/db-data:/data/db
